### ISSUE TITLE
Loading Oar file, terrain settings are not saved to regionsettings table.

### ISSUE THREAD

**Issue by Vinhold** [emperorstarfinder/My-Halcyon#17] opened 2018-06-26 03:42 UTC
Example case:
In a beta or test grid create a new region. Apply a new land terrain to the region. Put in custom terrain textures and blending settings for it. Make it really stand out different from the default region textures. 
Save the region as an oar file. 
Load the saved oar file into a production Halcyon grid. 
The region will load and the custom textures will apply. You can even see them in the viewer region terrain window all correct. Check the region's regionsettings table record, it will not have any of the texture UUIDs or settings to match. The data is not saved to that record. 
Shutdown and restart the region. The terrain textures and blending levels will all be reverted to the defaults seen in the regionsettings table record and the custom ones loaded will all be gone. This affects only the terrain textures and blending levels.

**Comment by emperorstarfinder** [comment] 2018-06-27 01:19
According to kf6kjg on the mirror of this issue at InWorldz/Halcyon:

Try waiting at least 5 minutes before the restart. Persistence is on a 5 minute interval. If that allows the reboot to come back up as expected then the problem is one of timing and we can discuss if persistence needs an additional rule for when it is triggered. If that does not, then there's a bug.

I do not agree with his assessment here.  Persistence does not nor should not have anything to do directly with loading an OAR and making sure the updated information is stored in the proper database tables.  Persistence is more for ensuring viewers get necessary updates about a scene in a timely manner.  These updates can take anywhere from 5 minutes to an hour depending on the size of the grid and how busy the grid is.

If InWorldz has made uploading an OAR reliant on persistence factors on their grid or in halcyon that will spell trouble in the long run and means you could wind up with a lot of people having trouble when loading an OAR.  Remember what might work for InWorldz may not necessarily work for other grids using the Halcyon architecture for many different reasons ranging from missing components that are InWorldz specific to how a grid is configured to even how an operating system and hardware are configured.

When loading an OAR this should be automatically sent to the database and the necessary updates inserted into the table almost immediately without delay.  The fact that Vinhold indicates that his viewer can, in fact, see the oar after its loaded tells me that the region is able to load the oar, however, when he logs out and back in or restarts the region the loaded oar disappears back to the state it was prior to the OAR being uploaded tells me something has timed out from the time the region server loads the oar to the point that updates are received by the database server.  

While my first impression tells me that the database server has for some reason closed the connection for a particular packet or has gone away during an upload of an OAR it is also possible that there is something a bit more sinister going on.

My recommendation for the database server is to add or update the following to the my.cnf file:

// by increasing the max allowed packets we are ensuring that the packets are being read in their entirety should they be over the standard size that MySQL server generally expects them to be.
max_allowed_packet = 100G

// By default the timeout on the mysql server is 300 seconds.  We can ensure this will not cause the mysql server from going away during uploads of oars by increasing the time to 3000 seconds.
connection_timeout = 3000

If by adding these to the my.cnf file and restarting the database server and retrying the upload works and the regionsettings table updates then we know it was likely because the mysql server closed the connection for a packet and went away.  However it still would be strange that it would do that with a very small OAR but we can ensure its not the MySQL server being the cause in this case.

More to come on this as I conduct some testing.

**Comment by emperorstarfinder** [comment] 2018-07-08 01:45
I ran into this problem this afternoon though not with the OAR.  Setting a parcel for sale took approximately a half hour and a viewer relog before the viewer was able to get the sale information.  However it did not insert this information into the actual DB table for parcel sales but the region is clearly sending the sale information somewhere.  The next question is where which may shed some light onto why @Vinhold is running into this when loading OARs.

**Comment by Vinhold** [comment] 2018-07-08 20:44
Update: It finally occurred to me to try changing a terrain setting after loading the oar. That I know forces a data change and save. It did. So now the known workaround is to load an oar file for a region, then edit any one of the terrain elevation entries, save it, then change it back and save it. That will update the regionsettings table and save all the terrain textures and elevations etc. So the primary problem still remains that the same data is not getting put into the regionsettings table when loading the oar.

**Comment by emperorstarfinder** [comment] 2018-07-08 21:51
Now that only proves that something isn't getting to where it should be in the database.  Next question will be the why? but at least we know the info is getting there.

**Comment by emperorstarfinder** [comment] 2018-08-11 00:57
Closing as this is now fixed in commit: https://github.com/emperorstarfinder/My-Halcyon/commit/929dde29147e257980e8e3c6736c6aa023a44341  If this persists reopen the issue with new information.

**Closed by emperorstarfinder** 2018-08-11 00:57 UTC
Labels: Resolved, bug
